# ═══════════════════════════════════════════════════════════════════
# AUTO-GENERATED by codegen.py — do not edit by hand
# Server  : sift-disk
# Tools   : 180
# Source  : registry.json
# ═══════════════════════════════════════════════════════════════════

import subprocess
import shutil
import sys
from datetime import datetime, timezone
from mcp.server.fastmcp import FastMCP
from shared import AuditLogger, OutputTruncator, ReadOnlyEnforcer

mcp   = FastMCP("sift-disk")
audit = AuditLogger("sift-disk")
trunc = OutputTruncator(max_chars=50_000)
guard = ReadOnlyEnforcer()


# ── helpers ──────────────────────────────────────────────────────────────────

def _run(binary: str, args: list, timeout: int = 300) -> dict:
    """
    Core subprocess runner used by every tool in this server.
    Returns a structured dict — never raw text.
    Logs every call to the audit trail.
    """
    resolved = shutil.which(binary)
    if not resolved:
        return {
            "error":     f"{binary} not found on PATH",
            "installed": False,
            "binary":    binary,
        }

    cmd   = [resolved] + [str(a) for a in args if a is not None and a != ""]
    start = datetime.now(timezone.utc)

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            stdin=subprocess.DEVNULL,
        )
        duration_ms = int(
            (datetime.now(timezone.utc) - start).total_seconds() * 1000
        )
        entry = {
            "tool":        binary,
            "server":      "sift-disk",
            "command":     " ".join(cmd),
            "exit_code":   result.returncode,
            "stdout":      trunc.truncate(result.stdout),
            "stderr":      result.stderr.strip() or None,
            "timestamp":   start.isoformat(),
            "duration_ms": duration_ms,
            "installed":   True,
        }

    except subprocess.TimeoutExpired:
        entry = {
            "tool":      binary,
            "server":    "sift-disk",
            "command":   " ".join(cmd),
            "error":     f"timeout after {timeout}s",
            "timestamp": start.isoformat(),
            "installed": True,
        }

    except Exception as e:
        entry = {
            "tool":      binary,
            "server":    "sift-disk",
            "command":   " ".join(cmd),
            "error":     str(e),
            "timestamp": start.isoformat(),
            "installed": True,
        }

    audit.log(entry)
    return entry


# ── tools ─────────────────────────────────────────────────────────────────────

@mcp.tool()
def tool_affcat(args: str = "") -> dict:
    """
    Run affcat (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affcat", arg_list)

@mcp.tool()
def tool_affcompare(args: str = "") -> dict:
    """
    Run affcompare (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affcompare", arg_list)

@mcp.tool()
def tool_affconvert(args: str = "") -> dict:
    """
    Run affconvert (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affconvert", arg_list)

@mcp.tool()
def tool_affcopy(args: str = "") -> dict:
    """
    Run affcopy (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affcopy", arg_list)

@mcp.tool()
def tool_affcrypto(args: str = "") -> dict:
    """
    Run affcrypto (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affcrypto", arg_list)

@mcp.tool()
def tool_affdiskprint(args: str = "") -> dict:
    """
    Run affdiskprint (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affdiskprint", arg_list)

@mcp.tool()
def tool_affinfo(args: str = "") -> dict:
    """
    Run affinfo (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affinfo", arg_list)

@mcp.tool()
def tool_affix(args: str = "") -> dict:
    """
    Run affix (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affix", arg_list)

@mcp.tool()
def tool_affrecover(args: str = "") -> dict:
    """
    Run affrecover (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affrecover", arg_list)

@mcp.tool()
def tool_affsegment(args: str = "") -> dict:
    """
    Run affsegment (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affsegment", arg_list)

@mcp.tool()
def tool_affsign(args: str = "") -> dict:
    """
    Run affsign (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affsign", arg_list)

@mcp.tool()
def tool_affstats(args: str = "") -> dict:
    """
    Run affstats (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affstats", arg_list)

@mcp.tool()
def tool_affuse(args: str = "") -> dict:
    """
    Run affuse (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affuse", arg_list)

@mcp.tool()
def tool_affverify(args: str = "") -> dict:
    """
    Run affverify (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affverify", arg_list)

@mcp.tool()
def tool_affxml(args: str = "") -> dict:
    """
    Run affxml (from package: afflib-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("affxml", arg_list)

@mcp.tool()
def tool_autopsy(args: str = "") -> dict:
    """
    Run autopsy (from package: autopsy).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("autopsy", arg_list)

@mcp.tool()
def tool_avfs_config(args: str = "") -> dict:
    """
    Run avfs-config (from package: avfs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("avfs-config", arg_list)

@mcp.tool()
def tool_avfsd(args: str = "") -> dict:
    """
    Run avfsd (from package: avfs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("avfsd", arg_list)

@mcp.tool()
def tool_davpass(args: str = "") -> dict:
    """
    Run davpass (from package: avfs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("davpass", arg_list)

@mcp.tool()
def tool_ftppass(args: str = "") -> dict:
    """
    Run ftppass (from package: avfs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ftppass", arg_list)

@mcp.tool()
def tool_mountavfs(args: str = "") -> dict:
    """
    Run mountavfs (from package: avfs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mountavfs", arg_list)

@mcp.tool()
def tool_umountavfs(args: str = "") -> dict:
    """
    Run umountavfs (from package: avfs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("umountavfs", arg_list)

@mcp.tool()
def tool_dc3dd(args: str = "") -> dict:
    """
    Run dc3dd (from package: dc3dd).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dc3dd", arg_list)

@mcp.tool()
def tool_dcfldd(args: str = "") -> dict:
    """
    Run dcfldd (from package: dcfldd).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dcfldd", arg_list)

@mcp.tool()
def tool_disktype(args: str = "") -> dict:
    """
    Run disktype (from package: disktype).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("disktype", arg_list)

@mcp.tool()
def tool_badblocks(args: str = "") -> dict:
    """
    Run badblocks (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("badblocks", arg_list)

@mcp.tool()
def tool_debugfs(args: str = "") -> dict:
    """
    Run debugfs (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("debugfs", arg_list)

@mcp.tool()
def tool_dumpe2fs(args: str = "") -> dict:
    """
    Run dumpe2fs (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dumpe2fs", arg_list)

@mcp.tool()
def tool_e2fsck(args: str = "") -> dict:
    """
    Run e2fsck (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("e2fsck", arg_list)

@mcp.tool()
def tool_e2image(args: str = "") -> dict:
    """
    Run e2image (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("e2image", arg_list)

@mcp.tool()
def tool_e2scrub(args: str = "") -> dict:
    """
    Run e2scrub (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("e2scrub", arg_list)

@mcp.tool()
def tool_e2scrub_all(args: str = "") -> dict:
    """
    Run e2scrub_all (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("e2scrub_all", arg_list)

@mcp.tool()
def tool_e2undo(args: str = "") -> dict:
    """
    Run e2undo (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("e2undo", arg_list)

@mcp.tool()
def tool_mke2fs(args: str = "") -> dict:
    """
    Run mke2fs (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mke2fs", arg_list)

@mcp.tool()
def tool_resize2fs(args: str = "") -> dict:
    """
    Run resize2fs (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("resize2fs", arg_list)

@mcp.tool()
def tool_tune2fs(args: str = "") -> dict:
    """
    Run tune2fs (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tune2fs", arg_list)

@mcp.tool()
def tool_chattr(args: str = "") -> dict:
    """
    Run chattr (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("chattr", arg_list)

@mcp.tool()
def tool_lsattr(args: str = "") -> dict:
    """
    Run lsattr (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("lsattr", arg_list)

@mcp.tool()
def tool_e2freefrag(args: str = "") -> dict:
    """
    Run e2freefrag (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("e2freefrag", arg_list)

@mcp.tool()
def tool_e4crypt(args: str = "") -> dict:
    """
    Run e4crypt (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("e4crypt", arg_list)

@mcp.tool()
def tool_e4defrag(args: str = "") -> dict:
    """
    Run e4defrag (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("e4defrag", arg_list)

@mcp.tool()
def tool_filefrag(args: str = "") -> dict:
    """
    Run filefrag (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("filefrag", arg_list)

@mcp.tool()
def tool_mklost_found(args: str = "") -> dict:
    """
    Run mklost+found (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mklost+found", arg_list)

@mcp.tool()
def tool_e2label(args: str = "") -> dict:
    """
    Run e2label (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("e2label", arg_list)

@mcp.tool()
def tool_e2mmpstatus(args: str = "") -> dict:
    """
    Run e2mmpstatus (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("e2mmpstatus", arg_list)

@mcp.tool()
def tool_fsck_ext2(args: str = "") -> dict:
    """
    Run fsck.ext2 (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fsck.ext2", arg_list)

@mcp.tool()
def tool_fsck_ext3(args: str = "") -> dict:
    """
    Run fsck.ext3 (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fsck.ext3", arg_list)

@mcp.tool()
def tool_fsck_ext4(args: str = "") -> dict:
    """
    Run fsck.ext4 (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fsck.ext4", arg_list)

@mcp.tool()
def tool_mkfs_ext2(args: str = "") -> dict:
    """
    Run mkfs.ext2 (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mkfs.ext2", arg_list)

@mcp.tool()
def tool_mkfs_ext3(args: str = "") -> dict:
    """
    Run mkfs.ext3 (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mkfs.ext3", arg_list)

@mcp.tool()
def tool_mkfs_ext4(args: str = "") -> dict:
    """
    Run mkfs.ext4 (from package: e2fsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mkfs.ext4", arg_list)

@mcp.tool()
def tool_mount_exfat_fuse(args: str = "") -> dict:
    """
    Run mount.exfat-fuse (from package: exfat-fuse).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mount.exfat-fuse", arg_list)

@mcp.tool()
def tool_exif(args: str = "") -> dict:
    """
    Run exif (from package: exif).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("exif", arg_list)

@mcp.tool()
def tool_extundelete(args: str = "") -> dict:
    """
    Run extundelete (from package: extundelete).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("extundelete", arg_list)

@mcp.tool()
def tool_fdupes(args: str = "") -> dict:
    """
    Run fdupes (from package: fdupes).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fdupes", arg_list)

@mcp.tool()
def tool_feh(args: str = "") -> dict:
    """
    Run feh (from package: feh).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("feh", arg_list)

@mcp.tool()
def tool_foremost(args: str = "") -> dict:
    """
    Run foremost (from package: foremost).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("foremost", arg_list)

@mcp.tool()
def tool_ddrescue(args: str = "") -> dict:
    """
    Run ddrescue (from package: gddrescue).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ddrescue", arg_list)

@mcp.tool()
def tool_ddrescuelog(args: str = "") -> dict:
    """
    Run ddrescuelog (from package: gddrescue).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ddrescuelog", arg_list)

@mcp.tool()
def tool_git(args: str = "") -> dict:
    """
    Run git (from package: git).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("git", arg_list)

@mcp.tool()
def tool_git_shell(args: str = "") -> dict:
    """
    Run git-shell (from package: git).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("git-shell", arg_list)

@mcp.tool()
def tool_git_receive_pack(args: str = "") -> dict:
    """
    Run git-receive-pack (from package: git).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("git-receive-pack", arg_list)

@mcp.tool()
def tool_git_upload_archive(args: str = "") -> dict:
    """
    Run git-upload-archive (from package: git).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("git-upload-archive", arg_list)

@mcp.tool()
def tool_git_upload_pack(args: str = "") -> dict:
    """
    Run git-upload-pack (from package: git).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("git-upload-pack", arg_list)

@mcp.tool()
def tool_gzrecover(args: str = "") -> dict:
    """
    Run gzrecover (from package: gzrt).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("gzrecover", arg_list)

@mcp.tool()
def tool_jq(args: str = "") -> dict:
    """
    Run jq (from package: jq).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("jq", arg_list)

@mcp.tool()
def tool_kpartx(args: str = "") -> dict:
    """
    Run kpartx (from package: kpartx).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("kpartx", arg_list)

@mcp.tool()
def tool_ewfacquire(args: str = "") -> dict:
    """
    Run ewfacquire (from package: libewf-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ewfacquire", arg_list)

@mcp.tool()
def tool_ewfacquirestream(args: str = "") -> dict:
    """
    Run ewfacquirestream (from package: libewf-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ewfacquirestream", arg_list)

@mcp.tool()
def tool_ewfdebug(args: str = "") -> dict:
    """
    Run ewfdebug (from package: libewf-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ewfdebug", arg_list)

@mcp.tool()
def tool_ewfexport(args: str = "") -> dict:
    """
    Run ewfexport (from package: libewf-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ewfexport", arg_list)

@mcp.tool()
def tool_ewfinfo(args: str = "") -> dict:
    """
    Run ewfinfo (from package: libewf-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ewfinfo", arg_list)

@mcp.tool()
def tool_ewfmount(args: str = "") -> dict:
    """
    Run ewfmount (from package: libewf-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ewfmount", arg_list)

@mcp.tool()
def tool_ewfrecover(args: str = "") -> dict:
    """
    Run ewfrecover (from package: libewf-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ewfrecover", arg_list)

@mcp.tool()
def tool_ewfverify(args: str = "") -> dict:
    """
    Run ewfverify (from package: libewf-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ewfverify", arg_list)

@mcp.tool()
def tool_fsapfsinfo(args: str = "") -> dict:
    """
    Run fsapfsinfo (from package: libfsapfs-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fsapfsinfo", arg_list)

@mcp.tool()
def tool_fsapfsmount(args: str = "") -> dict:
    """
    Run fsapfsmount (from package: libfsapfs-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fsapfsmount", arg_list)

@mcp.tool()
def tool_plistutil(args: str = "") -> dict:
    """
    Run plistutil (from package: libplist-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("plistutil", arg_list)

@mcp.tool()
def tool_nbd_client(args: str = "") -> dict:
    """
    Run nbd-client (from package: nbd-client).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nbd-client", arg_list)

@mcp.tool()
def tool_lowntfs_3g(args: str = "") -> dict:
    """
    Run lowntfs-3g (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("lowntfs-3g", arg_list)

@mcp.tool()
def tool_ntfs_3g(args: str = "") -> dict:
    """
    Run ntfs-3g (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfs-3g", arg_list)

@mcp.tool()
def tool_ntfs_3g_probe(args: str = "") -> dict:
    """
    Run ntfs-3g.probe (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfs-3g.probe", arg_list)

@mcp.tool()
def tool_ntfscat(args: str = "") -> dict:
    """
    Run ntfscat (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfscat", arg_list)

@mcp.tool()
def tool_ntfscluster(args: str = "") -> dict:
    """
    Run ntfscluster (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfscluster", arg_list)

@mcp.tool()
def tool_ntfscmp(args: str = "") -> dict:
    """
    Run ntfscmp (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfscmp", arg_list)

@mcp.tool()
def tool_ntfsfallocate(args: str = "") -> dict:
    """
    Run ntfsfallocate (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfsfallocate", arg_list)

@mcp.tool()
def tool_ntfsfix(args: str = "") -> dict:
    """
    Run ntfsfix (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfsfix", arg_list)

@mcp.tool()
def tool_ntfsinfo(args: str = "") -> dict:
    """
    Run ntfsinfo (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfsinfo", arg_list)

@mcp.tool()
def tool_ntfsls(args: str = "") -> dict:
    """
    Run ntfsls (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfsls", arg_list)

@mcp.tool()
def tool_ntfsmove(args: str = "") -> dict:
    """
    Run ntfsmove (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfsmove", arg_list)

@mcp.tool()
def tool_ntfsrecover(args: str = "") -> dict:
    """
    Run ntfsrecover (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfsrecover", arg_list)

@mcp.tool()
def tool_ntfssecaudit(args: str = "") -> dict:
    """
    Run ntfssecaudit (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfssecaudit", arg_list)

@mcp.tool()
def tool_ntfstruncate(args: str = "") -> dict:
    """
    Run ntfstruncate (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfstruncate", arg_list)

@mcp.tool()
def tool_ntfsusermap(args: str = "") -> dict:
    """
    Run ntfsusermap (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfsusermap", arg_list)

@mcp.tool()
def tool_ntfswipe(args: str = "") -> dict:
    """
    Run ntfswipe (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfswipe", arg_list)

@mcp.tool()
def tool_mkntfs(args: str = "") -> dict:
    """
    Run mkntfs (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mkntfs", arg_list)

@mcp.tool()
def tool_ntfsclone(args: str = "") -> dict:
    """
    Run ntfsclone (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfsclone", arg_list)

@mcp.tool()
def tool_ntfscp(args: str = "") -> dict:
    """
    Run ntfscp (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfscp", arg_list)

@mcp.tool()
def tool_ntfslabel(args: str = "") -> dict:
    """
    Run ntfslabel (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfslabel", arg_list)

@mcp.tool()
def tool_ntfsresize(args: str = "") -> dict:
    """
    Run ntfsresize (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfsresize", arg_list)

@mcp.tool()
def tool_ntfsundelete(args: str = "") -> dict:
    """
    Run ntfsundelete (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfsundelete", arg_list)

@mcp.tool()
def tool_ntfsdecrypt(args: str = "") -> dict:
    """
    Run ntfsdecrypt (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ntfsdecrypt", arg_list)

@mcp.tool()
def tool_mkfs_ntfs(args: str = "") -> dict:
    """
    Run mkfs.ntfs (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mkfs.ntfs", arg_list)

@mcp.tool()
def tool_mount_lowntfs_3g(args: str = "") -> dict:
    """
    Run mount.lowntfs-3g (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mount.lowntfs-3g", arg_list)

@mcp.tool()
def tool_mount_ntfs(args: str = "") -> dict:
    """
    Run mount.ntfs (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mount.ntfs", arg_list)

@mcp.tool()
def tool_mount_ntfs_3g(args: str = "") -> dict:
    """
    Run mount.ntfs-3g (from package: ntfs-3g).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mount.ntfs-3g", arg_list)

@mcp.tool()
def tool_7z(args: str = "") -> dict:
    """
    Run 7z (from package: p7zip-full).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("7z", arg_list)

@mcp.tool()
def tool_7za(args: str = "") -> dict:
    """
    Run 7za (from package: p7zip-full).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("7za", arg_list)

@mcp.tool()
def tool_qemu_img(args: str = "") -> dict:
    """
    Run qemu-img (from package: qemu-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("qemu-img", arg_list)

@mcp.tool()
def tool_qemu_io(args: str = "") -> dict:
    """
    Run qemu-io (from package: qemu-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("qemu-io", arg_list)

@mcp.tool()
def tool_qemu_nbd(args: str = "") -> dict:
    """
    Run qemu-nbd (from package: qemu-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("qemu-nbd", arg_list)

@mcp.tool()
def tool_qemu_make_debian_root(args: str = "") -> dict:
    """
    Run qemu-make-debian-root (from package: qemu-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("qemu-make-debian-root", arg_list)

@mcp.tool()
def tool_rar(args: str = "") -> dict:
    """
    Run rar (from package: rar).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("rar", arg_list)

@mcp.tool()
def tool_safecopy(args: str = "") -> dict:
    """
    Run safecopy (from package: safecopy).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("safecopy", arg_list)

@mcp.tool()
def tool_scalpel(args: str = "") -> dict:
    """
    Run scalpel (from package: scalpel).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("scalpel", arg_list)

@mcp.tool()
def tool_blkcalc(args: str = "") -> dict:
    """
    Run blkcalc (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("blkcalc", arg_list)

@mcp.tool()
def tool_blkcat(args: str = "") -> dict:
    """
    Run blkcat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("blkcat", arg_list)

@mcp.tool()
def tool_blkls(args: str = "") -> dict:
    """
    Run blkls (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("blkls", arg_list)

@mcp.tool()
def tool_blkstat(args: str = "") -> dict:
    """
    Run blkstat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("blkstat", arg_list)

@mcp.tool()
def tool_fcat(args: str = "") -> dict:
    """
    Run fcat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fcat", arg_list)

@mcp.tool()
def tool_ffind(args: str = "") -> dict:
    """
    Run ffind (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ffind", arg_list)

@mcp.tool()
def tool_fiwalk(args: str = "") -> dict:
    """
    Run fiwalk (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fiwalk", arg_list)

@mcp.tool()
def tool_fls(args: str = "") -> dict:
    """
    Run fls (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fls", arg_list)

@mcp.tool()
def tool_fsstat(args: str = "") -> dict:
    """
    Run fsstat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fsstat", arg_list)

@mcp.tool()
def tool_hfind(args: str = "") -> dict:
    """
    Run hfind (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("hfind", arg_list)

@mcp.tool()
def tool_icat(args: str = "") -> dict:
    """
    Run icat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("icat", arg_list)

@mcp.tool()
def tool_ifind(args: str = "") -> dict:
    """
    Run ifind (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ifind", arg_list)

@mcp.tool()
def tool_ils(args: str = "") -> dict:
    """
    Run ils (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ils", arg_list)

@mcp.tool()
def tool_img_cat(args: str = "") -> dict:
    """
    Run img_cat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("img_cat", arg_list)

@mcp.tool()
def tool_img_stat(args: str = "") -> dict:
    """
    Run img_stat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("img_stat", arg_list)

@mcp.tool()
def tool_istat(args: str = "") -> dict:
    """
    Run istat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("istat", arg_list)

@mcp.tool()
def tool_jcat(args: str = "") -> dict:
    """
    Run jcat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("jcat", arg_list)

@mcp.tool()
def tool_jls(args: str = "") -> dict:
    """
    Run jls (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("jls", arg_list)

@mcp.tool()
def tool_jpeg_extract(args: str = "") -> dict:
    """
    Run jpeg_extract (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("jpeg_extract", arg_list)

@mcp.tool()
def tool_mactime(args: str = "") -> dict:
    """
    Run mactime (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mactime", arg_list)

@mcp.tool()
def tool_mmcat(args: str = "") -> dict:
    """
    Run mmcat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mmcat", arg_list)

@mcp.tool()
def tool_mmls(args: str = "") -> dict:
    """
    Run mmls (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mmls", arg_list)

@mcp.tool()
def tool_mmstat(args: str = "") -> dict:
    """
    Run mmstat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mmstat", arg_list)

@mcp.tool()
def tool_pstat(args: str = "") -> dict:
    """
    Run pstat (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("pstat", arg_list)

@mcp.tool()
def tool_sigfind(args: str = "") -> dict:
    """
    Run sigfind (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("sigfind", arg_list)

@mcp.tool()
def tool_sorter(args: str = "") -> dict:
    """
    Run sorter (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("sorter", arg_list)

@mcp.tool()
def tool_srch_strings(args: str = "") -> dict:
    """
    Run srch_strings (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("srch_strings", arg_list)

@mcp.tool()
def tool_tsk_comparedir(args: str = "") -> dict:
    """
    Run tsk_comparedir (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tsk_comparedir", arg_list)

@mcp.tool()
def tool_tsk_gettimes(args: str = "") -> dict:
    """
    Run tsk_gettimes (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tsk_gettimes", arg_list)

@mcp.tool()
def tool_tsk_imageinfo(args: str = "") -> dict:
    """
    Run tsk_imageinfo (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tsk_imageinfo", arg_list)

@mcp.tool()
def tool_tsk_loaddb(args: str = "") -> dict:
    """
    Run tsk_loaddb (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tsk_loaddb", arg_list)

@mcp.tool()
def tool_tsk_recover(args: str = "") -> dict:
    """
    Run tsk_recover (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tsk_recover", arg_list)

@mcp.tool()
def tool_usnjls(args: str = "") -> dict:
    """
    Run usnjls (from package: sleuthkit).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("usnjls", arg_list)

@mcp.tool()
def tool_fidentify(args: str = "") -> dict:
    """
    Run fidentify (from package: testdisk).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fidentify", arg_list)

@mcp.tool()
def tool_photorec(args: str = "") -> dict:
    """
    Run photorec (from package: testdisk).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("photorec", arg_list)

@mcp.tool()
def tool_testdisk(args: str = "") -> dict:
    """
    Run testdisk (from package: testdisk).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("testdisk", arg_list)

@mcp.tool()
def tool_vbindiff(args: str = "") -> dict:
    """
    Run vbindiff (from package: vbindiff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("vbindiff", arg_list)

@mcp.tool()
def tool_debugvmfs(args: str = "") -> dict:
    """
    Run debugvmfs (from package: vmfs-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("debugvmfs", arg_list)

@mcp.tool()
def tool_fsck_vmfs(args: str = "") -> dict:
    """
    Run fsck.vmfs (from package: vmfs-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fsck.vmfs", arg_list)

@mcp.tool()
def tool_vmfs_fuse(args: str = "") -> dict:
    """
    Run vmfs-fuse (from package: vmfs-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("vmfs-fuse", arg_list)

@mcp.tool()
def tool_vmfs_lvm(args: str = "") -> dict:
    """
    Run vmfs-lvm (from package: vmfs-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("vmfs-lvm", arg_list)

@mcp.tool()
def tool_fsck_xfs(args: str = "") -> dict:
    """
    Run fsck.xfs (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fsck.xfs", arg_list)

@mcp.tool()
def tool_mkfs_xfs(args: str = "") -> dict:
    """
    Run mkfs.xfs (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mkfs.xfs", arg_list)

@mcp.tool()
def tool_xfs_repair(args: str = "") -> dict:
    """
    Run xfs_repair (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_repair", arg_list)

@mcp.tool()
def tool_xfs_admin(args: str = "") -> dict:
    """
    Run xfs_admin (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_admin", arg_list)

@mcp.tool()
def tool_xfs_bmap(args: str = "") -> dict:
    """
    Run xfs_bmap (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_bmap", arg_list)

@mcp.tool()
def tool_xfs_copy(args: str = "") -> dict:
    """
    Run xfs_copy (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_copy", arg_list)

@mcp.tool()
def tool_xfs_db(args: str = "") -> dict:
    """
    Run xfs_db (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_db", arg_list)

@mcp.tool()
def tool_xfs_estimate(args: str = "") -> dict:
    """
    Run xfs_estimate (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_estimate", arg_list)

@mcp.tool()
def tool_xfs_freeze(args: str = "") -> dict:
    """
    Run xfs_freeze (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_freeze", arg_list)

@mcp.tool()
def tool_xfs_fsr(args: str = "") -> dict:
    """
    Run xfs_fsr (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_fsr", arg_list)

@mcp.tool()
def tool_xfs_growfs(args: str = "") -> dict:
    """
    Run xfs_growfs (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_growfs", arg_list)

@mcp.tool()
def tool_xfs_info(args: str = "") -> dict:
    """
    Run xfs_info (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_info", arg_list)

@mcp.tool()
def tool_xfs_io(args: str = "") -> dict:
    """
    Run xfs_io (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_io", arg_list)

@mcp.tool()
def tool_xfs_logprint(args: str = "") -> dict:
    """
    Run xfs_logprint (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_logprint", arg_list)

@mcp.tool()
def tool_xfs_mdrestore(args: str = "") -> dict:
    """
    Run xfs_mdrestore (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_mdrestore", arg_list)

@mcp.tool()
def tool_xfs_metadump(args: str = "") -> dict:
    """
    Run xfs_metadump (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_metadump", arg_list)

@mcp.tool()
def tool_xfs_mkfile(args: str = "") -> dict:
    """
    Run xfs_mkfile (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_mkfile", arg_list)

@mcp.tool()
def tool_xfs_ncheck(args: str = "") -> dict:
    """
    Run xfs_ncheck (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_ncheck", arg_list)

@mcp.tool()
def tool_xfs_quota(args: str = "") -> dict:
    """
    Run xfs_quota (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_quota", arg_list)

@mcp.tool()
def tool_xfs_rtcp(args: str = "") -> dict:
    """
    Run xfs_rtcp (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_rtcp", arg_list)

@mcp.tool()
def tool_xfs_scrub(args: str = "") -> dict:
    """
    Run xfs_scrub (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_scrub", arg_list)

@mcp.tool()
def tool_xfs_scrub_all(args: str = "") -> dict:
    """
    Run xfs_scrub_all (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_scrub_all", arg_list)

@mcp.tool()
def tool_xfs_spaceman(args: str = "") -> dict:
    """
    Run xfs_spaceman (from package: xfsprogs).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xfs_spaceman", arg_list)

@mcp.tool()
def tool_xmount(args: str = "") -> dict:
    """
    Run xmount (from package: xmount).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xmount", arg_list)


# ── server entry point ────────────────────────────────────────────────────────

def main():
    """Console-script entry point used by pyproject.toml [project.scripts]."""
    mcp.run()


if __name__ == "__main__":
    main()
