# ═══════════════════════════════════════════════════════════════════
# AUTO-GENERATED by codegen.py — do not edit by hand
# Server  : sift-crypto
# Tools   : 28
# Source  : registry.json
# ═══════════════════════════════════════════════════════════════════

import subprocess
import shutil
import sys
from datetime import datetime, timezone
from mcp.server.fastmcp import FastMCP
from shared import AuditLogger, OutputTruncator, ReadOnlyEnforcer

mcp   = FastMCP("sift-crypto")
audit = AuditLogger("sift-crypto")
trunc = OutputTruncator(max_chars=50_000)
guard = ReadOnlyEnforcer()


# ── helpers ──────────────────────────────────────────────────────────────────

def _run(binary: str, args: list, timeout: int = 300) -> dict:
    """
    Core subprocess runner used by every tool in this server.
    Returns a structured dict — never raw text.
    Logs every call to the audit trail.
    """
    resolved = shutil.which(binary)
    if not resolved:
        return {
            "error":     f"{binary} not found on PATH",
            "installed": False,
            "binary":    binary,
        }

    cmd   = [resolved] + [str(a) for a in args if a is not None and a != ""]
    start = datetime.now(timezone.utc)

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        duration_ms = int(
            (datetime.now(timezone.utc) - start).total_seconds() * 1000
        )
        entry = {
            "tool":        binary,
            "server":      "sift-crypto",
            "command":     " ".join(cmd),
            "exit_code":   result.returncode,
            "stdout":      trunc.truncate(result.stdout),
            "stderr":      result.stderr.strip() or None,
            "timestamp":   start.isoformat(),
            "duration_ms": duration_ms,
            "installed":   True,
        }

    except subprocess.TimeoutExpired:
        entry = {
            "tool":      binary,
            "server":    "sift-crypto",
            "command":   " ".join(cmd),
            "error":     f"timeout after {timeout}s",
            "timestamp": start.isoformat(),
            "installed": True,
        }

    except Exception as e:
        entry = {
            "tool":      binary,
            "server":    "sift-crypto",
            "command":   " ".join(cmd),
            "error":     str(e),
            "timestamp": start.isoformat(),
            "installed": True,
        }

    audit.log(entry)
    return entry


# ── tools ─────────────────────────────────────────────────────────────────────

@mcp.tool()
def tool_ccguess(args: str = "") -> dict:
    """
    Run ccguess (from package: ccrypt).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ccguess", arg_list)

@mcp.tool()
def tool_ccrypt(args: str = "") -> dict:
    """
    Run ccrypt (from package: ccrypt).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ccrypt", arg_list)

@mcp.tool()
def tool_ccat(args: str = "") -> dict:
    """
    Run ccat (from package: ccrypt).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ccat", arg_list)

@mcp.tool()
def tool_ccdecrypt(args: str = "") -> dict:
    """
    Run ccdecrypt (from package: ccrypt).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ccdecrypt", arg_list)

@mcp.tool()
def tool_ccencrypt(args: str = "") -> dict:
    """
    Run ccencrypt (from package: ccrypt).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ccencrypt", arg_list)

@mcp.tool()
def tool_cmospwd(args: str = "") -> dict:
    """
    Run cmospwd (from package: cmospwd).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("cmospwd", arg_list)

@mcp.tool()
def tool_cryptdisks_start(args: str = "") -> dict:
    """
    Run cryptdisks_start (from package: cryptsetup).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("cryptdisks_start", arg_list)

@mcp.tool()
def tool_cryptdisks_stop(args: str = "") -> dict:
    """
    Run cryptdisks_stop (from package: cryptsetup).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("cryptdisks_stop", arg_list)

@mcp.tool()
def tool_luksformat(args: str = "") -> dict:
    """
    Run luksformat (from package: cryptsetup).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("luksformat", arg_list)

@mcp.tool()
def tool_dislocker_bek(args: str = "") -> dict:
    """
    Run dislocker-bek (from package: dislocker).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dislocker-bek", arg_list)

@mcp.tool()
def tool_dislocker_file(args: str = "") -> dict:
    """
    Run dislocker-file (from package: dislocker).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dislocker-file", arg_list)

@mcp.tool()
def tool_dislocker_find(args: str = "") -> dict:
    """
    Run dislocker-find (from package: dislocker).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dislocker-find", arg_list)

@mcp.tool()
def tool_dislocker_fuse(args: str = "") -> dict:
    """
    Run dislocker-fuse (from package: dislocker).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dislocker-fuse", arg_list)

@mcp.tool()
def tool_dislocker_metadata(args: str = "") -> dict:
    """
    Run dislocker-metadata (from package: dislocker).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dislocker-metadata", arg_list)

@mcp.tool()
def tool_dislocker(args: str = "") -> dict:
    """
    Run dislocker (from package: dislocker).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dislocker", arg_list)

@mcp.tool()
def tool_dpl4hydra(args: str = "") -> dict:
    """
    Run dpl4hydra (from package: hydra).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dpl4hydra", arg_list)

@mcp.tool()
def tool_hydra(args: str = "") -> dict:
    """
    Run hydra (from package: hydra).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("hydra", arg_list)

@mcp.tool()
def tool_hydra_wizard(args: str = "") -> dict:
    """
    Run hydra-wizard (from package: hydra).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("hydra-wizard", arg_list)

@mcp.tool()
def tool_pw_inspector(args: str = "") -> dict:
    """
    Run pw-inspector (from package: hydra).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("pw-inspector", arg_list)

@mcp.tool()
def tool_fvdeinfo(args: str = "") -> dict:
    """
    Run fvdeinfo (from package: libfvde-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fvdeinfo", arg_list)

@mcp.tool()
def tool_fvdemount(args: str = "") -> dict:
    """
    Run fvdemount (from package: libfvde-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fvdemount", arg_list)

@mcp.tool()
def tool_fvdewipekey(args: str = "") -> dict:
    """
    Run fvdewipekey (from package: libfvde-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("fvdewipekey", arg_list)

@mcp.tool()
def tool_ophcrack(args: str = "") -> dict:
    """
    Run ophcrack (from package: ophcrack).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ophcrack", arg_list)

@mcp.tool()
def tool_ophcrack_cli(args: str = "") -> dict:
    """
    Run ophcrack-cli (from package: ophcrack-cli).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ophcrack-cli", arg_list)

@mcp.tool()
def tool_histogram(args: str = "") -> dict:
    """
    Run histogram (from package: outguess).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("histogram", arg_list)

@mcp.tool()
def tool_outguess(args: str = "") -> dict:
    """
    Run outguess (from package: outguess).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("outguess", arg_list)

@mcp.tool()
def tool_seek_script(args: str = "") -> dict:
    """
    Run seek_script (from package: outguess).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("seek_script", arg_list)

@mcp.tool()
def tool_outguess_extract(args: str = "") -> dict:
    """
    Run outguess-extract (from package: outguess).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("outguess-extract", arg_list)


# ── server entry point ────────────────────────────────────────────────────────

def main():
    """Console-script entry point used by pyproject.toml [project.scripts]."""
    mcp.run()


if __name__ == "__main__":
    main()
