# ═══════════════════════════════════════════════════════════════════
# AUTO-GENERATED by codegen.py — do not edit by hand
# Server  : sift-network
# Tools   : 96
# Source  : registry.json
# ═══════════════════════════════════════════════════════════════════

import subprocess
import shutil
import sys
from datetime import datetime, timezone
from mcp.server.fastmcp import FastMCP
from shared import AuditLogger, OutputTruncator, ReadOnlyEnforcer

mcp   = FastMCP("sift-network")
audit = AuditLogger("sift-network")
trunc = OutputTruncator(max_chars=50_000)
guard = ReadOnlyEnforcer()


# ── helpers ──────────────────────────────────────────────────────────────────

def _run(binary: str, args: list, timeout: int = 300) -> dict:
    """
    Core subprocess runner used by every tool in this server.
    Returns a structured dict — never raw text.
    Logs every call to the audit trail.
    """
    resolved = shutil.which(binary)
    if not resolved:
        return {
            "error":     f"{binary} not found on PATH",
            "installed": False,
            "binary":    binary,
        }

    cmd   = [resolved] + [str(a) for a in args if a is not None and a != ""]
    start = datetime.now(timezone.utc)

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            stdin=subprocess.DEVNULL,
        )
        duration_ms = int(
            (datetime.now(timezone.utc) - start).total_seconds() * 1000
        )
        entry = {
            "tool":        binary,
            "server":      "sift-network",
            "command":     " ".join(cmd),
            "exit_code":   result.returncode,
            "stdout":      trunc.truncate(result.stdout),
            "stderr":      result.stderr.strip() or None,
            "timestamp":   start.isoformat(),
            "duration_ms": duration_ms,
            "installed":   True,
        }

    except subprocess.TimeoutExpired:
        entry = {
            "tool":      binary,
            "server":    "sift-network",
            "command":   " ".join(cmd),
            "error":     f"timeout after {timeout}s",
            "timestamp": start.isoformat(),
            "installed": True,
        }

    except Exception as e:
        entry = {
            "tool":      binary,
            "server":    "sift-network",
            "command":   " ".join(cmd),
            "error":     str(e),
            "timestamp": start.isoformat(),
            "installed": True,
        }

    audit.log(entry)
    return entry


# ── tools ─────────────────────────────────────────────────────────────────────

@mcp.tool()
def tool_aircrack_ng(args: str = "") -> dict:
    """
    Run aircrack-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("aircrack-ng", arg_list)

@mcp.tool()
def tool_airdecap_ng(args: str = "") -> dict:
    """
    Run airdecap-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("airdecap-ng", arg_list)

@mcp.tool()
def tool_airdecloak_ng(args: str = "") -> dict:
    """
    Run airdecloak-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("airdecloak-ng", arg_list)

@mcp.tool()
def tool_airolib_ng(args: str = "") -> dict:
    """
    Run airolib-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("airolib-ng", arg_list)

@mcp.tool()
def tool_besside_ng_crawler(args: str = "") -> dict:
    """
    Run besside-ng-crawler (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("besside-ng-crawler", arg_list)

@mcp.tool()
def tool_buddy_ng(args: str = "") -> dict:
    """
    Run buddy-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("buddy-ng", arg_list)

@mcp.tool()
def tool_dcrack(args: str = "") -> dict:
    """
    Run dcrack (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dcrack", arg_list)

@mcp.tool()
def tool_ivstools(args: str = "") -> dict:
    """
    Run ivstools (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ivstools", arg_list)

@mcp.tool()
def tool_kstats(args: str = "") -> dict:
    """
    Run kstats (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("kstats", arg_list)

@mcp.tool()
def tool_makeivs_ng(args: str = "") -> dict:
    """
    Run makeivs-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("makeivs-ng", arg_list)

@mcp.tool()
def tool_packetforge_ng(args: str = "") -> dict:
    """
    Run packetforge-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("packetforge-ng", arg_list)

@mcp.tool()
def tool_wpaclean(args: str = "") -> dict:
    """
    Run wpaclean (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("wpaclean", arg_list)

@mcp.tool()
def tool_airbase_ng(args: str = "") -> dict:
    """
    Run airbase-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("airbase-ng", arg_list)

@mcp.tool()
def tool_aireplay_ng(args: str = "") -> dict:
    """
    Run aireplay-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("aireplay-ng", arg_list)

@mcp.tool()
def tool_airmon_ng(args: str = "") -> dict:
    """
    Run airmon-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("airmon-ng", arg_list)

@mcp.tool()
def tool_airodump_ng(args: str = "") -> dict:
    """
    Run airodump-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("airodump-ng", arg_list)

@mcp.tool()
def tool_airodump_ng_oui_update(args: str = "") -> dict:
    """
    Run airodump-ng-oui-update (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("airodump-ng-oui-update", arg_list)

@mcp.tool()
def tool_airserv_ng(args: str = "") -> dict:
    """
    Run airserv-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("airserv-ng", arg_list)

@mcp.tool()
def tool_airtun_ng(args: str = "") -> dict:
    """
    Run airtun-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("airtun-ng", arg_list)

@mcp.tool()
def tool_airventriloquist_ng(args: str = "") -> dict:
    """
    Run airventriloquist-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("airventriloquist-ng", arg_list)

@mcp.tool()
def tool_besside_ng(args: str = "") -> dict:
    """
    Run besside-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("besside-ng", arg_list)

@mcp.tool()
def tool_easside_ng(args: str = "") -> dict:
    """
    Run easside-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("easside-ng", arg_list)

@mcp.tool()
def tool_tkiptun_ng(args: str = "") -> dict:
    """
    Run tkiptun-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tkiptun-ng", arg_list)

@mcp.tool()
def tool_wesside_ng(args: str = "") -> dict:
    """
    Run wesside-ng (from package: aircrack-ng).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("wesside-ng", arg_list)

@mcp.tool()
def tool_arp_fingerprint(args: str = "") -> dict:
    """
    Run arp-fingerprint (from package: arp-scan).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("arp-fingerprint", arg_list)

@mcp.tool()
def tool_arp_scan(args: str = "") -> dict:
    """
    Run arp-scan (from package: arp-scan).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("arp-scan", arg_list)

@mcp.tool()
def tool_get_iab(args: str = "") -> dict:
    """
    Run get-iab (from package: arp-scan).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("get-iab", arg_list)

@mcp.tool()
def tool_get_oui(args: str = "") -> dict:
    """
    Run get-oui (from package: arp-scan).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("get-oui", arg_list)

@mcp.tool()
def tool_mount_cifs(args: str = "") -> dict:
    """
    Run mount.cifs (from package: cifs-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mount.cifs", arg_list)

@mcp.tool()
def tool_cifscreds(args: str = "") -> dict:
    """
    Run cifscreds (from package: cifs-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("cifscreds", arg_list)

@mcp.tool()
def tool_getcifsacl(args: str = "") -> dict:
    """
    Run getcifsacl (from package: cifs-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("getcifsacl", arg_list)

@mcp.tool()
def tool_setcifsacl(args: str = "") -> dict:
    """
    Run setcifsacl (from package: cifs-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("setcifsacl", arg_list)

@mcp.tool()
def tool_smb2_quota(args: str = "") -> dict:
    """
    Run smb2-quota (from package: cifs-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("smb2-quota", arg_list)

@mcp.tool()
def tool_smbinfo(args: str = "") -> dict:
    """
    Run smbinfo (from package: cifs-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("smbinfo", arg_list)

@mcp.tool()
def tool_cifs_idmap(args: str = "") -> dict:
    """
    Run cifs.idmap (from package: cifs-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("cifs.idmap", arg_list)

@mcp.tool()
def tool_cifs_upcall(args: str = "") -> dict:
    """
    Run cifs.upcall (from package: cifs-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("cifs.upcall", arg_list)

@mcp.tool()
def tool_mount_smb3(args: str = "") -> dict:
    """
    Run mount.smb3 (from package: cifs-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mount.smb3", arg_list)

@mcp.tool()
def tool_cryptcat(args: str = "") -> dict:
    """
    Run cryptcat (from package: cryptcat).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("cryptcat", arg_list)

@mcp.tool()
def tool_driftnet(args: str = "") -> dict:
    """
    Run driftnet (from package: driftnet).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("driftnet", arg_list)

@mcp.tool()
def tool_arpspoof(args: str = "") -> dict:
    """
    Run arpspoof (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("arpspoof", arg_list)

@mcp.tool()
def tool_dnsspoof(args: str = "") -> dict:
    """
    Run dnsspoof (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dnsspoof", arg_list)

@mcp.tool()
def tool_dsniff(args: str = "") -> dict:
    """
    Run dsniff (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("dsniff", arg_list)

@mcp.tool()
def tool_filesnarf(args: str = "") -> dict:
    """
    Run filesnarf (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("filesnarf", arg_list)

@mcp.tool()
def tool_macof(args: str = "") -> dict:
    """
    Run macof (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("macof", arg_list)

@mcp.tool()
def tool_mailsnarf(args: str = "") -> dict:
    """
    Run mailsnarf (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("mailsnarf", arg_list)

@mcp.tool()
def tool_msgsnarf(args: str = "") -> dict:
    """
    Run msgsnarf (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("msgsnarf", arg_list)

@mcp.tool()
def tool_sshmitm(args: str = "") -> dict:
    """
    Run sshmitm (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("sshmitm", arg_list)

@mcp.tool()
def tool_sshow(args: str = "") -> dict:
    """
    Run sshow (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("sshow", arg_list)

@mcp.tool()
def tool_tcpkill(args: str = "") -> dict:
    """
    Run tcpkill (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpkill", arg_list)

@mcp.tool()
def tool_tcpnice(args: str = "") -> dict:
    """
    Run tcpnice (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpnice", arg_list)

@mcp.tool()
def tool_urlsnarf(args: str = "") -> dict:
    """
    Run urlsnarf (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("urlsnarf", arg_list)

@mcp.tool()
def tool_webmitm(args: str = "") -> dict:
    """
    Run webmitm (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("webmitm", arg_list)

@mcp.tool()
def tool_webspy(args: str = "") -> dict:
    """
    Run webspy (from package: dsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("webspy", arg_list)

@mcp.tool()
def tool_etherape(args: str = "") -> dict:
    """
    Run etherape (from package: etherape).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("etherape", arg_list)

@mcp.tool()
def tool_ettercap(args: str = "") -> dict:
    """
    Run ettercap (from package: ettercap-graphical).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ettercap", arg_list)

@mcp.tool()
def tool_ettercap_pkexec(args: str = "") -> dict:
    """
    Run ettercap-pkexec (from package: ettercap-graphical).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ettercap-pkexec", arg_list)

@mcp.tool()
def tool_etterfilter(args: str = "") -> dict:
    """
    Run etterfilter (from package: ettercap-graphical).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("etterfilter", arg_list)

@mcp.tool()
def tool_etterlog(args: str = "") -> dict:
    """
    Run etterlog (from package: ettercap-graphical).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("etterlog", arg_list)

@mcp.tool()
def tool_grepcidr(args: str = "") -> dict:
    """
    Run grepcidr (from package: grepcidr).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("grepcidr", arg_list)

@mcp.tool()
def tool_lft(args: str = "") -> dict:
    """
    Run lft (from package: lft).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("lft", arg_list)

@mcp.tool()
def tool_whob(args: str = "") -> dict:
    """
    Run whob (from package: lft).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("whob", arg_list)

@mcp.tool()
def tool_nbtscan(args: str = "") -> dict:
    """
    Run nbtscan (from package: nbtscan).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nbtscan", arg_list)

@mcp.tool()
def tool_netsed(args: str = "") -> dict:
    """
    Run netsed (from package: netsed).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("netsed", arg_list)

@mcp.tool()
def tool_netwox(args: str = "") -> dict:
    """
    Run netwox (from package: netwox).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("netwox", arg_list)

@mcp.tool()
def tool_nfanon(args: str = "") -> dict:
    """
    Run nfanon (from package: nfdump).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nfanon", arg_list)

@mcp.tool()
def tool_nfcapd(args: str = "") -> dict:
    """
    Run nfcapd (from package: nfdump).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nfcapd", arg_list)

@mcp.tool()
def tool_nfdump(args: str = "") -> dict:
    """
    Run nfdump (from package: nfdump).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nfdump", arg_list)

@mcp.tool()
def tool_nfexpire(args: str = "") -> dict:
    """
    Run nfexpire (from package: nfdump).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nfexpire", arg_list)

@mcp.tool()
def tool_nfpcapd(args: str = "") -> dict:
    """
    Run nfpcapd (from package: nfdump).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nfpcapd", arg_list)

@mcp.tool()
def tool_nfprofile(args: str = "") -> dict:
    """
    Run nfprofile (from package: nfdump).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nfprofile", arg_list)

@mcp.tool()
def tool_nfreplay(args: str = "") -> dict:
    """
    Run nfreplay (from package: nfdump).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nfreplay", arg_list)

@mcp.tool()
def tool_nftrack(args: str = "") -> dict:
    """
    Run nftrack (from package: nfdump).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nftrack", arg_list)

@mcp.tool()
def tool_ngrep(args: str = "") -> dict:
    """
    Run ngrep (from package: ngrep).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ngrep", arg_list)

@mcp.tool()
def tool_nikto(args: str = "") -> dict:
    """
    Run nikto (from package: nikto).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nikto", arg_list)

@mcp.tool()
def tool_p0f(args: str = "") -> dict:
    """
    Run p0f (from package: p0f).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("p0f", arg_list)

@mcp.tool()
def tool_filan(args: str = "") -> dict:
    """
    Run filan (from package: socat).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("filan", arg_list)

@mcp.tool()
def tool_procan(args: str = "") -> dict:
    """
    Run procan (from package: socat).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("procan", arg_list)

@mcp.tool()
def tool_socat(args: str = "") -> dict:
    """
    Run socat (from package: socat).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("socat", arg_list)

@mcp.tool()
def tool_ssldump(args: str = "") -> dict:
    """
    Run ssldump (from package: ssldump).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ssldump", arg_list)

@mcp.tool()
def tool_sslsniff(args: str = "") -> dict:
    """
    Run sslsniff (from package: sslsniff).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("sslsniff", arg_list)

@mcp.tool()
def tool_tcpflow(args: str = "") -> dict:
    """
    Run tcpflow (from package: tcpflow).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpflow", arg_list)

@mcp.tool()
def tool_tcpick(args: str = "") -> dict:
    """
    Run tcpick (from package: tcpick).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpick", arg_list)

@mcp.tool()
def tool_tcpbridge(args: str = "") -> dict:
    """
    Run tcpbridge (from package: tcpreplay).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpbridge", arg_list)

@mcp.tool()
def tool_tcpcapinfo(args: str = "") -> dict:
    """
    Run tcpcapinfo (from package: tcpreplay).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpcapinfo", arg_list)

@mcp.tool()
def tool_tcpliveplay(args: str = "") -> dict:
    """
    Run tcpliveplay (from package: tcpreplay).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpliveplay", arg_list)

@mcp.tool()
def tool_tcpprep(args: str = "") -> dict:
    """
    Run tcpprep (from package: tcpreplay).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpprep", arg_list)

@mcp.tool()
def tool_tcpreplay(args: str = "") -> dict:
    """
    Run tcpreplay (from package: tcpreplay).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpreplay", arg_list)

@mcp.tool()
def tool_tcpreplay_edit(args: str = "") -> dict:
    """
    Run tcpreplay-edit (from package: tcpreplay).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpreplay-edit", arg_list)

@mcp.tool()
def tool_tcprewrite(args: str = "") -> dict:
    """
    Run tcprewrite (from package: tcpreplay).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcprewrite", arg_list)

@mcp.tool()
def tool_tcpslice(args: str = "") -> dict:
    """
    Run tcpslice (from package: tcpslice).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpslice", arg_list)

@mcp.tool()
def tool_tcpprof(args: str = "") -> dict:
    """
    Run tcpprof (from package: tcpstat).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpprof", arg_list)

@mcp.tool()
def tool_tcpstat(args: str = "") -> dict:
    """
    Run tcpstat (from package: tcpstat).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpstat", arg_list)

@mcp.tool()
def tool_tcptrace(args: str = "") -> dict:
    """
    Run tcptrace (from package: tcptrace).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcptrace", arg_list)

@mcp.tool()
def tool_xpl2gpl(args: str = "") -> dict:
    """
    Run xpl2gpl (from package: tcptrace).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("xpl2gpl", arg_list)

@mcp.tool()
def tool_tcptrack(args: str = "") -> dict:
    """
    Run tcptrack (from package: tcptrack).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcptrack", arg_list)

@mcp.tool()
def tool_tcpxtract(args: str = "") -> dict:
    """
    Run tcpxtract (from package: tcpxtract).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tcpxtract", arg_list)


# ── server entry point ────────────────────────────────────────────────────────

def main():
    """Console-script entry point used by pyproject.toml [project.scripts]."""
    mcp.run()


if __name__ == "__main__":
    main()
