# ═══════════════════════════════════════════════════════════════════
# AUTO-GENERATED by codegen.py — do not edit by hand
# Server  : sift-hashing
# Tools   : 7
# Source  : registry.json
# ═══════════════════════════════════════════════════════════════════

import subprocess
import shutil
import sys
from datetime import datetime, timezone
from mcp.server.fastmcp import FastMCP
from shared import AuditLogger, OutputTruncator, ReadOnlyEnforcer

mcp   = FastMCP("sift-hashing")
audit = AuditLogger("sift-hashing")
trunc = OutputTruncator(max_chars=50_000)
guard = ReadOnlyEnforcer()


# ── helpers ──────────────────────────────────────────────────────────────────

def _run(binary: str, args: list, timeout: int = 300) -> dict:
    """
    Core subprocess runner used by every tool in this server.
    Returns a structured dict — never raw text.
    Logs every call to the audit trail.
    """
    resolved = shutil.which(binary)
    if not resolved:
        return {
            "error":     f"{binary} not found on PATH",
            "installed": False,
            "binary":    binary,
        }

    cmd   = [resolved] + [str(a) for a in args if a is not None and a != ""]
    start = datetime.now(timezone.utc)

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        duration_ms = int(
            (datetime.now(timezone.utc) - start).total_seconds() * 1000
        )
        entry = {
            "tool":        binary,
            "server":      "sift-hashing",
            "command":     " ".join(cmd),
            "exit_code":   result.returncode,
            "stdout":      trunc.truncate(result.stdout),
            "stderr":      result.stderr.strip() or None,
            "timestamp":   start.isoformat(),
            "duration_ms": duration_ms,
            "installed":   True,
        }

    except subprocess.TimeoutExpired:
        entry = {
            "tool":      binary,
            "server":    "sift-hashing",
            "command":   " ".join(cmd),
            "error":     f"timeout after {timeout}s",
            "timestamp": start.isoformat(),
            "installed": True,
        }

    except Exception as e:
        entry = {
            "tool":      binary,
            "server":    "sift-hashing",
            "command":   " ".join(cmd),
            "error":     str(e),
            "timestamp": start.isoformat(),
            "installed": True,
        }

    audit.log(entry)
    return entry


# ── tools ─────────────────────────────────────────────────────────────────────

@mcp.tool()
def tool_hashdeep(args: str = "") -> dict:
    """
    Run hashdeep (from package: hashdeep).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("hashdeep", arg_list)

@mcp.tool()
def tool_md5deep(args: str = "") -> dict:
    """
    Run md5deep (from package: hashdeep).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("md5deep", arg_list)

@mcp.tool()
def tool_sha1deep(args: str = "") -> dict:
    """
    Run sha1deep (from package: hashdeep).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("sha1deep", arg_list)

@mcp.tool()
def tool_sha256deep(args: str = "") -> dict:
    """
    Run sha256deep (from package: hashdeep).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("sha256deep", arg_list)

@mcp.tool()
def tool_tigerdeep(args: str = "") -> dict:
    """
    Run tigerdeep (from package: hashdeep).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("tigerdeep", arg_list)

@mcp.tool()
def tool_whirlpooldeep(args: str = "") -> dict:
    """
    Run whirlpooldeep (from package: hashdeep).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("whirlpooldeep", arg_list)

@mcp.tool()
def tool_ssdeep(args: str = "") -> dict:
    """
    Run ssdeep (from package: ssdeep).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ssdeep", arg_list)


# ── server entry point ────────────────────────────────────────────────────────

def main():
    """Console-script entry point used by pyproject.toml [project.scripts]."""
    mcp.run()


if __name__ == "__main__":
    main()
