# ═══════════════════════════════════════════════════════════════════
# AUTO-GENERATED by codegen.py — do not edit by hand
# Server  : sift-memory
# Tools   : 5
# Source  : registry.json
# ═══════════════════════════════════════════════════════════════════

import subprocess
import shutil
import sys
from datetime import datetime, timezone
from mcp.server.fastmcp import FastMCP
from shared import AuditLogger, OutputTruncator, ReadOnlyEnforcer

mcp   = FastMCP("sift-memory")
audit = AuditLogger("sift-memory")
trunc = OutputTruncator(max_chars=50_000)
guard = ReadOnlyEnforcer()


# ── helpers ──────────────────────────────────────────────────────────────────

def _run(binary: str, args: list, timeout: int = 300) -> dict:
    """
    Core subprocess runner used by every tool in this server.
    Returns a structured dict — never raw text.
    Logs every call to the audit trail.
    """
    resolved = shutil.which(binary)
    if not resolved:
        return {
            "error":     f"{binary} not found on PATH",
            "installed": False,
            "binary":    binary,
        }

    cmd   = [resolved] + [str(a) for a in args if a is not None and a != ""]
    start = datetime.now(timezone.utc)

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        duration_ms = int(
            (datetime.now(timezone.utc) - start).total_seconds() * 1000
        )
        entry = {
            "tool":        binary,
            "server":      "sift-memory",
            "command":     " ".join(cmd),
            "exit_code":   result.returncode,
            "stdout":      trunc.truncate(result.stdout),
            "stderr":      result.stderr.strip() or None,
            "timestamp":   start.isoformat(),
            "duration_ms": duration_ms,
            "installed":   True,
        }

    except subprocess.TimeoutExpired:
        entry = {
            "tool":      binary,
            "server":    "sift-memory",
            "command":   " ".join(cmd),
            "error":     f"timeout after {timeout}s",
            "timestamp": start.isoformat(),
            "installed": True,
        }

    except Exception as e:
        entry = {
            "tool":      binary,
            "server":    "sift-memory",
            "command":   " ".join(cmd),
            "error":     str(e),
            "timestamp": start.isoformat(),
            "installed": True,
        }

    audit.log(entry)
    return entry


# ── tools ─────────────────────────────────────────────────────────────────────

@mcp.tool()
def tool_aeskeyfind(args: str = "") -> dict:
    """
    Run aeskeyfind (from package: aeskeyfind).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("aeskeyfind", arg_list)

@mcp.tool()
def tool_bulk_extractor(args: str = "") -> dict:
    """
    Run bulk_extractor (from package: bulk-extractor).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("bulk_extractor", arg_list)

@mcp.tool()
def tool_plugin_test(args: str = "") -> dict:
    """
    Run plugin_test (from package: bulk-extractor).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("plugin_test", arg_list)

@mcp.tool()
def tool_ent(args: str = "") -> dict:
    """
    Run ent (from package: ent).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("ent", arg_list)

@mcp.tool()
def tool_rsakeyfind(args: str = "") -> dict:
    """
    Run rsakeyfind (from package: rsakeyfind).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("rsakeyfind", arg_list)


# ── server entry point ────────────────────────────────────────────────────────

def main():
    """Console-script entry point used by pyproject.toml [project.scripts]."""
    mcp.run()


if __name__ == "__main__":
    main()
