# ═══════════════════════════════════════════════════════════════════
# AUTO-GENERATED by codegen.py — do not edit by hand
# Server  : sift-windows
# Tools   : 27
# Source  : registry.json
# ═══════════════════════════════════════════════════════════════════

import subprocess
import shutil
import sys
from datetime import datetime, timezone
from mcp.server.fastmcp import FastMCP
from shared import AuditLogger, OutputTruncator, ReadOnlyEnforcer

mcp   = FastMCP("sift-windows")
audit = AuditLogger("sift-windows")
trunc = OutputTruncator(max_chars=50_000)
guard = ReadOnlyEnforcer()


# ── helpers ──────────────────────────────────────────────────────────────────

def _run(binary: str, args: list, timeout: int = 300) -> dict:
    """
    Core subprocess runner used by every tool in this server.
    Returns a structured dict — never raw text.
    Logs every call to the audit trail.
    """
    resolved = shutil.which(binary)
    if not resolved:
        return {
            "error":     f"{binary} not found on PATH",
            "installed": False,
            "binary":    binary,
        }

    cmd   = [resolved] + [str(a) for a in args if a is not None and a != ""]
    start = datetime.now(timezone.utc)

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            stdin=subprocess.DEVNULL,
        )
        duration_ms = int(
            (datetime.now(timezone.utc) - start).total_seconds() * 1000
        )
        entry = {
            "tool":        binary,
            "server":      "sift-windows",
            "command":     " ".join(cmd),
            "exit_code":   result.returncode,
            "stdout":      trunc.truncate(result.stdout),
            "stderr":      result.stderr.strip() or None,
            "timestamp":   start.isoformat(),
            "duration_ms": duration_ms,
            "installed":   True,
        }

    except subprocess.TimeoutExpired:
        entry = {
            "tool":      binary,
            "server":    "sift-windows",
            "command":   " ".join(cmd),
            "error":     f"timeout after {timeout}s",
            "timestamp": start.isoformat(),
            "installed": True,
        }

    except Exception as e:
        entry = {
            "tool":      binary,
            "server":    "sift-windows",
            "command":   " ".join(cmd),
            "error":     str(e),
            "timestamp": start.isoformat(),
            "installed": True,
        }

    audit.log(entry)
    return entry


# ── tools ─────────────────────────────────────────────────────────────────────

@mcp.tool()
def tool_cabextract(args: str = "") -> dict:
    """
    Run cabextract (from package: cabextract).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("cabextract", arg_list)

@mcp.tool()
def tool_esedbexport(args: str = "") -> dict:
    """
    Run esedbexport (from package: libesedb-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("esedbexport", arg_list)

@mcp.tool()
def tool_esedbinfo(args: str = "") -> dict:
    """
    Run esedbinfo (from package: libesedb-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("esedbinfo", arg_list)

@mcp.tool()
def tool_evtexport(args: str = "") -> dict:
    """
    Run evtexport (from package: libevt-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("evtexport", arg_list)

@mcp.tool()
def tool_evtinfo(args: str = "") -> dict:
    """
    Run evtinfo (from package: libevt-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("evtinfo", arg_list)

@mcp.tool()
def tool_evtxexport(args: str = "") -> dict:
    """
    Run evtxexport (from package: libevtx-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("evtxexport", arg_list)

@mcp.tool()
def tool_evtxinfo(args: str = "") -> dict:
    """
    Run evtxinfo (from package: libevtx-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("evtxinfo", arg_list)

@mcp.tool()
def tool_regfexport(args: str = "") -> dict:
    """
    Run regfexport (from package: libregf-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("regfexport", arg_list)

@mcp.tool()
def tool_regfinfo(args: str = "") -> dict:
    """
    Run regfinfo (from package: libregf-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("regfinfo", arg_list)

@mcp.tool()
def tool_regfmount(args: str = "") -> dict:
    """
    Run regfmount (from package: libregf-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("regfmount", arg_list)

@mcp.tool()
def tool_vshadowdebug(args: str = "") -> dict:
    """
    Run vshadowdebug (from package: libvshadow-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("vshadowdebug", arg_list)

@mcp.tool()
def tool_vshadowinfo(args: str = "") -> dict:
    """
    Run vshadowinfo (from package: libvshadow-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("vshadowinfo", arg_list)

@mcp.tool()
def tool_vshadowmount(args: str = "") -> dict:
    """
    Run vshadowmount (from package: libvshadow-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("vshadowmount", arg_list)

@mcp.tool()
def tool_pffexport(args: str = "") -> dict:
    """
    Run pffexport (from package: pff-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("pffexport", arg_list)

@mcp.tool()
def tool_pffinfo(args: str = "") -> dict:
    """
    Run pffinfo (from package: pff-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("pffinfo", arg_list)

@mcp.tool()
def tool_image_export_py(args: str = "") -> dict:
    """
    Run image_export.py (from package: plaso-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("image_export.py", arg_list)

@mcp.tool()
def tool_log2timeline_py(args: str = "") -> dict:
    """
    Run log2timeline.py (from package: plaso-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("log2timeline.py", arg_list)

@mcp.tool()
def tool_pinfo_py(args: str = "") -> dict:
    """
    Run pinfo.py (from package: plaso-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("pinfo.py", arg_list)

@mcp.tool()
def tool_psort_py(args: str = "") -> dict:
    """
    Run psort.py (from package: plaso-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("psort.py", arg_list)

@mcp.tool()
def tool_psteal_py(args: str = "") -> dict:
    """
    Run psteal.py (from package: plaso-tools).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("psteal.py", arg_list)

@mcp.tool()
def tool_pwsh(args: str = "") -> dict:
    """
    Run pwsh (from package: powershell).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("pwsh", arg_list)

@mcp.tool()
def tool_lspst(args: str = "") -> dict:
    """
    Run lspst (from package: pst-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("lspst", arg_list)

@mcp.tool()
def tool_nick2ldif(args: str = "") -> dict:
    """
    Run nick2ldif (from package: pst-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("nick2ldif", arg_list)

@mcp.tool()
def tool_pst2dii(args: str = "") -> dict:
    """
    Run pst2dii (from package: pst-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("pst2dii", arg_list)

@mcp.tool()
def tool_pst2ldif(args: str = "") -> dict:
    """
    Run pst2ldif (from package: pst-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("pst2ldif", arg_list)

@mcp.tool()
def tool_readpst(args: str = "") -> dict:
    """
    Run readpst (from package: pst-utils).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("readpst", arg_list)

@mcp.tool()
def tool_samdump2(args: str = "") -> dict:
    """
    Run samdump2 (from package: samdump2).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("samdump2", arg_list)


# ── server entry point ────────────────────────────────────────────────────────

def main():
    """Console-script entry point used by pyproject.toml [project.scripts]."""
    mcp.run()


if __name__ == "__main__":
    main()
