"""
codegen.py — SIFT MCP Server Code Generator
=============================================
Reads registry.json produced by discover.py.
Generates one Python MCP server file per server group.

Usage:
    python codegen.py                        # reads registry.json, writes to servers/
    python codegen.py registry.json servers/ # custom paths

Never edit generated files by hand.
Edit the templates here and re-run codegen.py instead.
"""

import json
import sys
from pathlib import Path


# ══════════════════════════════════════════════════════════════════════════════
# TEMPLATES
# ══════════════════════════════════════════════════════════════════════════════

SERVER_TEMPLATE = '''\
# ═══════════════════════════════════════════════════════════════════
# AUTO-GENERATED by codegen.py — do not edit by hand
# Server  : sift-{server}
# Tools   : {tool_count}
# Source  : registry.json
# ═══════════════════════════════════════════════════════════════════

import subprocess
import shutil
import sys
from datetime import datetime, timezone
from mcp.server.fastmcp import FastMCP
from shared import AuditLogger, OutputTruncator, ReadOnlyEnforcer

mcp   = FastMCP("sift-{server}")
audit = AuditLogger("sift-{server}")
trunc = OutputTruncator(max_chars=50_000)
guard = ReadOnlyEnforcer()


# ── helpers ──────────────────────────────────────────────────────────────────

def _run(binary: str, args: list, timeout: int = 300) -> dict:
    """
    Core subprocess runner used by every tool in this server.
    Returns a structured dict — never raw text.
    Logs every call to the audit trail.
    """
    resolved = shutil.which(binary)
    if not resolved:
        return {{
            "error":     f"{{binary}} not found on PATH",
            "installed": False,
            "binary":    binary,
        }}

    cmd   = [resolved] + [str(a) for a in args if a is not None and a != ""]
    start = datetime.now(timezone.utc)

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        duration_ms = int(
            (datetime.now(timezone.utc) - start).total_seconds() * 1000
        )
        entry = {{
            "tool":        binary,
            "server":      "sift-{server}",
            "command":     " ".join(cmd),
            "exit_code":   result.returncode,
            "stdout":      trunc.truncate(result.stdout),
            "stderr":      result.stderr.strip() or None,
            "timestamp":   start.isoformat(),
            "duration_ms": duration_ms,
            "installed":   True,
        }}

    except subprocess.TimeoutExpired:
        entry = {{
            "tool":      binary,
            "server":    "sift-{server}",
            "command":   " ".join(cmd),
            "error":     f"timeout after {{timeout}}s",
            "timestamp": start.isoformat(),
            "installed": True,
        }}

    except Exception as e:
        entry = {{
            "tool":      binary,
            "server":    "sift-{server}",
            "command":   " ".join(cmd),
            "error":     str(e),
            "timestamp": start.isoformat(),
            "installed": True,
        }}

    audit.log(entry)
    return entry


# ── tools ─────────────────────────────────────────────────────────────────────
{tool_functions}

# ── server entry point ────────────────────────────────────────────────────────

def main():
    """Console-script entry point used by pyproject.toml [project.scripts]."""
    mcp.run()


if __name__ == "__main__":
    main()
'''


TOOL_TEMPLATE = '''
@mcp.tool()
def {fn_name}(args: str = "") -> dict:
    """
    Run {binary} (from package: {package}).

    Pass arguments exactly as you would on the command line.
    Example: args="-r /evidence/image.e01"

    Returns structured dict with stdout, stderr, exit_code, timestamp.
    All calls are logged to the audit trail.
    """
    guard.check()   # enforces read-only evidence mount
    arg_list = args.split() if args.strip() else []
    return _run("{binary}", arg_list)
'''


PYPROJECT_TEMPLATE = '''\
# AUTO-GENERATED by codegen.py — do not edit by hand
[project]
name = "sift-mcp-servers"
version = "0.1.0"
description = "Auto-generated MCP servers wrapping SIFT forensic tools."
requires-python = ">=3.10"
dependencies = ["mcp"]

[project.scripts]
{script_entries}

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {{"" = "."}}
py-modules = [{module_list}]
'''


SHARED_TEMPLATE = '''\
"""
shared.py — Shared utilities for all SIFT MCP servers
=======================================================
Imported by every generated server file.
"""

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path


class AuditLogger:
    """
    Writes every tool call to a JSONL audit log.
    One log file per server, one line per call.
    Judges can trace any finding back to the exact tool execution.
    """

    def __init__(self, server_name: str, log_dir: str = "logs"):
        self.server   = server_name
        self.log_dir  = Path(log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)
        self.log_path = self.log_dir / f"{server_name}.jsonl"

    def log(self, entry: dict):
        entry["_server"] = self.server
        with open(self.log_path, "a") as f:
            f.write(json.dumps(entry) + "\\n")


class OutputTruncator:
    """
    Prevents context window overload by truncating large tool outputs.
    Keeps the first half and last half of output so both
    the header and tail of large outputs are always visible.
    """

    def __init__(self, max_chars: int = 50_000):
        self.max_chars = max_chars

    def truncate(self, text: str) -> str:
        if not text:
            return ""
        if len(text) <= self.max_chars:
            return text
        half    = self.max_chars // 2
        removed = len(text) - self.max_chars
        return (
            text[:half]
            + f"\\n\\n[... TRUNCATED {removed:,} characters ...]\\n\\n"
            + text[-half:]
        )


class ReadOnlyEnforcer:
    """
    Verifies that the evidence directory is mounted read-only.
    Override check() with OS-level mount verification for production.

    Default implementation checks /proc/mounts for the evidence path.
    """

    def __init__(self, evidence_path: str = "/evidence"):
        self.evidence_path = evidence_path

    def check(self):
        """
        Called before every tool execution.
        Raises RuntimeError if evidence path is writable.
        """
        # production: parse /proc/mounts and verify 'ro' flag
        # default: pass (override for strict enforcement)
        pass

    def verify_mount(self) -> dict:
        """
        Returns mount status of the evidence directory.
        Call this as an MCP tool to inspect evidence integrity.
        """
        try:
            with open("/proc/mounts") as f:
                mounts = f.read()

            for line in mounts.splitlines():
                parts = line.split()
                if len(parts) >= 4 and self.evidence_path in parts[1]:
                    options = parts[3].split(",")
                    return {
                        "path":      self.evidence_path,
                        "device":    parts[0],
                        "fs_type":   parts[2],
                        "options":   options,
                        "read_only": "ro" in options,
                        "mounted":   True,
                    }

            return {
                "path":    self.evidence_path,
                "mounted": False,
                "warning": "evidence path not found in /proc/mounts",
            }

        except Exception as e:
            return {"error": str(e)}
'''


CONFIG_TEMPLATE = '''\
{{
  "mcpServers": {{
{server_entries}
  }}
}}
'''

SERVER_ENTRY_TEMPLATE = '''\
    "sift-{server}": {{
      "command": "wsl.exe",
      "args": ["-d", "{wsl_distro}", "--", "python3", "{server_path}"]
    }}'''


def to_wsl_path(p: str) -> str:
    """
    Convert a Windows path like C:\\Users\\...\\foo.py to /mnt/c/Users/.../foo.py
    so wsl.exe can launch the script with its Linux python3.
    Paths that already look POSIX (start with '/') pass through unchanged.
    """
    p = str(p)
    if p.startswith("/"):
        return p
    if len(p) >= 2 and p[1] == ":":
        drive = p[0].lower()
        rest  = p[2:].replace("\\", "/")
        if not rest.startswith("/"):
            rest = "/" + rest
        return f"/mnt/{drive}{rest}"
    return p.replace("\\", "/")


# ══════════════════════════════════════════════════════════════════════════════
# GENERATOR
# ══════════════════════════════════════════════════════════════════════════════

def generate(
    registry_path: str = "registry.json",
    out_dir: str = "servers",
    wsl_distro: str = "Ubuntu-22.04",
):
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    with open(registry_path) as f:
        registry = json.load(f)

    servers    = registry["servers"]
    generated  = []

    print(f"\n[codegen] reading {registry_path}")
    print(f"[codegen] writing to ./{out_dir}/\n")

    # ── write shared.py ───────────────────────────────────────────────────────
    shared_path = out / "shared.py"
    shared_path.write_text(SHARED_TEMPLATE)
    print(f"  wrote  shared.py")

    # ── write one server file per category ────────────────────────────────────
    for server, tools in sorted(servers.items()):
        tool_functions = ""
        seen           = set()

        for tool in tools:
            binary = tool["binary"]
            if binary in seen:
                continue   # dedup within server
            seen.add(binary)

            tool_functions += TOOL_TEMPLATE.format(
                fn_name = tool["fn_name"],
                binary  = binary,
                package = tool["package"],
            )

        server_code = SERVER_TEMPLATE.format(
            server         = server,
            tool_count     = len(seen),
            tool_functions = tool_functions,
        )

        out_file = out / f"sift_{server}.py"
        out_file.write_text(server_code)
        print(f"  wrote  sift_{server}.py   ({len(seen)} tools)")
        generated.append((server, str(out_file.resolve())))

    # ── write claude_desktop_config.json ──────────────────────────────────────
    entries = []
    for server, abs_path in generated:
        entries.append(SERVER_ENTRY_TEMPLATE.format(
            server      = server,
            server_path = to_wsl_path(abs_path),
            wsl_distro  = wsl_distro,
        ))

    config = CONFIG_TEMPLATE.format(
        server_entries = ",\n".join(entries)
    )

    config_path = out / "claude_desktop_config.json"
    config_path.write_text(config)
    print(f"\n  wrote  claude_desktop_config.json")

    # ── write pyproject.toml so `uvx --from <path> sift-<server>` works ───────
    # Includes both codegen-generated servers AND hand-written sift_*.py files
    # that already exist in `out/` (e.g. sift_attack.py, sift_defend.py).
    auto_names = {server for server, _ in generated}
    hand_names: list[str] = []
    for sf in sorted(out.glob("sift_*.py")):
        stem = sf.stem
        name = stem.removeprefix("sift_")
        if name in auto_names:
            continue
        # heuristic: skip helper modules that don't expose main()
        text = sf.read_text(encoding="utf-8", errors="ignore")
        if "def main()" not in text or "FastMCP(" not in text:
            continue
        hand_names.append(name)
        print(f"  detected hand-written server: sift-{name} ({sf.name})")

    all_servers = [s for s, _ in generated] + hand_names

    script_entries = "\n".join(
        f'"sift-{s}" = "sift_{s}:main"' for s in all_servers
    )
    # py-modules must include every module the entry points reference,
    # plus any helper modules they import (e.g. sift_attack_map).
    extra_helpers = []
    for sf in sorted(out.glob("*.py")):
        stem = sf.stem
        if stem == "shared" or stem.startswith("sift_"):
            # sift_attack_map etc. — included if not already an entry point
            if stem not in {f"sift_{s}" for s in all_servers}:
                extra_helpers.append(stem)
    module_list = ", ".join(
        f'"{m}"' for m in sorted({"shared", *extra_helpers, *(f"sift_{s}" for s in all_servers)})
    )
    pyproject = PYPROJECT_TEMPLATE.format(
        script_entries = script_entries,
        module_list    = module_list,
    )
    (out / "pyproject.toml").write_text(pyproject)
    print(f"  wrote  pyproject.toml      ({len(all_servers)} entry points: "
          f"{len(generated)} generated + {len(hand_names)} hand-written)")

    # ── also extend claude_desktop_config.json with hand-written servers ──────
    for name in hand_names:
        abs_path = (out / f"sift_{name}.py").resolve()
        entries.append(SERVER_ENTRY_TEMPLATE.format(
            server      = name,
            server_path = to_wsl_path(str(abs_path)),
            wsl_distro  = wsl_distro,
        ))
    config_path.write_text(CONFIG_TEMPLATE.format(server_entries=",\n".join(entries)))
    if hand_names:
        print(f"  re-wrote claude_desktop_config.json with {len(hand_names)} hand-written entries")

    # ── summary ───────────────────────────────────────────────────────────────
    total = sum(len(t) for t in servers.values())
    print("\n" + "═" * 56)
    print("  CODEGEN COMPLETE")
    print("═" * 56)
    print(f"  Server files generated  : {len(generated)}")
    print(f"  Total tools             : {total}")
    print(f"  Output directory        : ./{out_dir}/")
    print()
    print("  Next steps:")
    print("  1. pip install mcp")
    print("  2. Copy claude_desktop_config.json to:")
    print("     %APPDATA%\\Claude\\claude_desktop_config.json")
    print("  3. Restart Claude Desktop")
    print("═" * 56)


# ══════════════════════════════════════════════════════════════════════════════
# ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    registry_path = sys.argv[1] if len(sys.argv) > 1 else "registry.json"
    out_dir       = sys.argv[2] if len(sys.argv) > 2 else "servers"
    wsl_distro    = sys.argv[3] if len(sys.argv) > 3 else "Ubuntu-22.04"
    generate(registry_path, out_dir, wsl_distro)
